/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    GlobalBottom: typeof import('./src/components/GlobalBottom.vue')['default']
    GlobalTop: typeof import('./src/components/GlobalTop.vue')['default']
    LeftNav: typeof import('./src/components/LeftNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

